apiVersion: apps/v1
kind: Deployment
metadata:
  name: pt-magic
  labels:
    app: pt-magic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pt-magic
  template:
    metadata:
      labels:
        app: pt-magic
    spec:
      containers:
        - name: pt-magic
          imagePullPolicy: Never
          image: pt-magic:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "128Mi"
