name: 'Build and Deploy to Cloud Run'

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

env:
  PROJECT_ID: "${{ secrets.PROJECT_ID }}"
  WIP: "${{ secrets.WIP }}"
  REGION: "${{ vars.REGION }}"
  ARTIFACT_REPO: "${{ vars.ARTIFACT_REPO }}"
  SERVICE: "${{ vars.SERVICE_NAME }}"
  IMAGE: "${{ vars.IMAGE_NAME }}"
  DOCKER_BASE: "${{ vars.DOCKER_BASE }}"

permissions:
  contents: read
  id-token: write # Required for requesting the JWT from GitHub OIDC provider

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          project_id: ${{ env.PROJECT_ID }}
          workload_identity_provider: ${{ env.WIP }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: 'Docker Auth'
        run: |-
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: 'Build and Push Container'
        run: |-
          DOCKER_TAG="${{ env.DOCKER_BASE }}/${{ env.ARTIFACT_REPO }}/${{ env.IMAGE }}:${{ github.sha }}"
          echo "DOCKER_TAG=${DOCKER_TAG}" >> "$GITHUB_ENV"
          docker build --tag "${DOCKER_TAG}" .
          docker push "${DOCKER_TAG}"

      - name: 'Deploy to Cloud Run'
        id: 'deploy'
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: '${{ env.SERVICE }}'
          region: '${{ env.REGION }}'
          image: '${{ env.DOCKER_TAG }}'

      - name: 'Show output'
        run: echo "Deployed to ${{ steps.deploy.outputs.url }}"
